# Site settings
title: Hoora's Blog
email: hoora.rezaei@live.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Hoora Rezaei Moghaddam
your-title: Machine Learning Engineer

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url: https://gitlab.com/hrezaeim
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/hoorarezaeim/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/RMHoora

# Build settings
markdown: kramdown
